version: '3.1'
services:
  postgres:
    image: postgres:15.4
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
  mysql:
    image: mysql:8.1.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
    volumes:
      - ./.data/mysql/data:/var/lib/mysql
  mongo:
    image: mongo:6.0.7
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./.data/mongo/data:/data/db
